services:
  api:
    image: ${DOCKER_REGISTRY-}scmsapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Database__Provider=PostgreSql
      - Database__EnsureCreated=false
      - ConnectionStrings__PostgreSqlConnection=Host=scms_db;Database=SCMS_db;Username=postgres;Password=admin;
    depends_on:
      - scms_db

  scms_db:
    image: postgres:17-alpine
    container_name: scms_db
    environment:
      POSTGRES_DB: SCMS_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
      - ./seed.realworld.sql:/docker-entrypoint-initdb.d/zz-seed.realworld.sql
    ports:
      - "5432:5432"

volumes:
  postgres_data:
